import type { AttentionPacket, PacketItem, PublicIssue, PublicPullRequest, PublicRepoSummary, QueueHealth } from "./types";

const SECURITY_RE = /\b(cve|vulnerability|exploit|rce|xss|csrf|sql injection|auth bypass|privilege escalation|secret|token leak|credential|sandbox escape)\b/i;
const AI_RE = /\b(ai generated|ai-generated|chatgpt|claude|copilot|cursor|generated by ai|llm|vibe coded|vibe-coded)\b/i;
const LOW_CONTEXT_RE = /\b(fix|fixed|update|improve|refactor|issue|bug|problem|doesn't work|not working)\b/i;
const BEHAVIOR_RE = /\b(api|flag|config|behavior|deprecat|breaking|remove|default|validation|cli|feature gate|user-visible)\b/i;
const SUPPORT_RE = /\b(how do i|question|help|install|setup|configure|usage|what is the way|can someone)\b/i;
const REPRO_RE = /\b(repro|reproduction|steps|version|environment|expected|actual|logs?|stack trace)\b/i;

function clamp(score: number) {
  return Math.max(0, Math.min(100, Math.round(score)));
}

function ageDays(updatedAt: string) {
  return Math.max(0, Math.round((Date.now() - new Date(updatedAt).getTime()) / 86_400_000));
}

function textOf(item: { title: string; body: string }) {
  return `${item.title}\n${item.body}`;
}

function missingRepro(issue: PublicIssue) {
  return issue.body.length < 600 && !REPRO_RE.test(textOf(issue));
}

function likelyAiIssue(issue: PublicIssue) {
  const text = textOf(issue);
  if (AI_RE.test(text)) return true;
  return issue.body.length < 280 && LOW_CONTEXT_RE.test(issue.title) && !REPRO_RE.test(text);
}

function likelyAiPr(pr: PublicPullRequest) {
  const text = textOf(pr);
  if (AI_RE.test(text)) return true;
  return pr.body.length < 220 && LOW_CONTEXT_RE.test(pr.title) && (pr.daysStale > 3 || pr.comments + pr.reviewComments === 0);
}

function tokenize(value: string) {
  return new Set(
    value
      .toLowerCase()
      .replace(/[^a-z0-9 ]/g, " ")
      .split(/\s+/)
      .filter((word) => word.length > 3)
  );
}

function similarity(a: string, b: string) {
  const left = tokenize(a);
  const right = tokenize(b);
  if (left.size === 0 || right.size === 0) return 0;
  let overlap = 0;
  for (const token of left) {
    if (right.has(token)) overlap += 1;
  }
  return overlap / Math.max(left.size, right.size);
}

function item(input: Omit<PacketItem, "score"> & { score: number }): PacketItem {
  return { ...input, score: clamp(input.score) };
}

function issueItem(issue: PublicIssue, label: string, score: number, why: string, evidence: string[], nextStep: string): PacketItem {
  return item({
    id: `issue:${issue.number}:${label}`,
    type: "issue",
    reference: `#${issue.number}`,
    title: issue.title,
    url: issue.url,
    score,
    label,
    why,
    evidence,
    nextStep,
  });
}

function prItem(pr: PublicPullRequest, label: string, score: number, why: string, evidence: string[], nextStep: string): PacketItem {
  return item({
    id: `pr:${pr.number}:${label}`,
    type: "pr",
    reference: `PR #${pr.number}`,
    title: pr.title,
    url: pr.url,
    score,
    label,
    why,
    evidence,
    nextStep,
  });
}

export function buildAttentionPacket(repo: PublicRepoSummary, issues: PublicIssue[], prs: PublicPullRequest[]): AttentionPacket {
  const stalePrs = prs.filter((pr) => pr.daysStale >= 14);
  const noReproIssues = issues.filter(missingRepro);
  const securityIssues = issues.filter((issue) => SECURITY_RE.test(textOf(issue)));
  const securityPrs = prs.filter((pr) => SECURITY_RE.test(textOf(pr)));
  const aiIssueItems = issues.filter(likelyAiIssue).map((issue) =>
    issueItem(
      issue,
      "Likely AI slop / low-context issue",
      70 + (missingRepro(issue) ? 10 : 0),
      "The report has little actionable detail and matches common low-context issue patterns.",
      [
        `${issue.body.length} body characters`,
        missingRepro(issue) ? "Missing version/environment/reproduction signals" : "Some reproduction signal present",
        `${issue.comments} comments`,
      ],
      "Do not spend maintainer time until the reporter adds reproduction details or AI disclosure."
    )
  );
  const aiPrItems = prs.filter(likelyAiPr).map((pr) =>
    prItem(
      pr,
      "Likely AI slop / disclosure needed",
      72 + (pr.body.length < 120 ? 8 : 0),
      "The PR has low author context relative to the review burden.",
      [
        `${pr.body.length} body characters`,
        `${pr.daysStale}d since last update`,
        `${pr.comments + pr.reviewComments} discussion comments`,
      ],
      "Ask the author to explain intent, testing, and whether AI generated the change before deep review."
    )
  );

  const riskyPrs = prs
    .filter((pr) => pr.daysStale >= 14 || SECURITY_RE.test(textOf(pr)) || BEHAVIOR_RE.test(textOf(pr)) || likelyAiPr(pr))
    .map((pr) =>
      prItem(
        pr,
        SECURITY_RE.test(textOf(pr)) ? "Security-sensitive PR" : BEHAVIOR_RE.test(textOf(pr)) ? "Behavior/docs risk" : "Review attention needed",
        58 + pr.daysStale * 1.5 + (SECURITY_RE.test(textOf(pr)) ? 25 : 0) + (BEHAVIOR_RE.test(textOf(pr)) ? 14 : 0),
        "This PR is likely to consume maintainer judgment before it can move.",
        [
          `${pr.daysStale}d stale`,
          `${pr.comments + pr.reviewComments} comments`,
          pr.isDraft ? "Draft PR" : "Open PR",
        ],
        "Open the PR packet first if it touches user behavior, security, or maintainer-blocked review."
      )
    );

  const issueTriage = [
    ...noReproIssues.map((issue) =>
      issueItem(
        issue,
        SUPPORT_RE.test(textOf(issue)) ? "Support disguised as issue" : "Missing reproduction",
        55 + (issue.comments > 3 ? 10 : 0),
        "This is unlikely to be actionable without more reporter detail.",
        [
          `${issue.body.length} body characters`,
          `${issue.comments} comments`,
          SUPPORT_RE.test(textOf(issue)) ? "Support/question language detected" : "Required bug fields not visible",
        ],
        "Ask for version, environment, exact steps, expected behavior, actual behavior, and logs."
      )
    ),
    ...securityIssues.map((issue) =>
      issueItem(
        issue,
        "Security-looking thread",
        92,
        "Security language appears in a public issue and needs careful maintainer handling.",
        ["Security keyword detected", `${issue.comments} comments`, `${ageDays(issue.updatedAt)}d since update`],
        "Review privately before making public claims or asking for exploit details."
      )
    ),
  ];

  const duplicateCandidates: PacketItem[] = [];
  for (let i = 0; i < issues.length; i += 1) {
    const matches = issues
      .slice(i + 1)
      .map((candidate) => ({ candidate, score: similarity(issues[i].title, candidate.title) }))
      .filter((match) => match.score >= 0.42)
      .slice(0, 3);
    if (matches.length > 0) {
      duplicateCandidates.push(
        item({
          id: `cluster:${issues[i].number}`,
          type: "cluster",
          reference: `#${issues[i].number}`,
          title: issues[i].title,
          url: issues[i].url,
          score: 64 + matches.length * 6,
          label: "Possible duplicate cluster",
          why: "Multiple open issues have overlapping titles and may share one canonical thread.",
          evidence: matches.map((match) => `#${match.candidate.number}: ${match.candidate.title}`),
          nextStep: "Pick or create one canonical thread before more maintainer time spreads across duplicates.",
        })
      );
    }
  }

  const docsReleaseImpact = prs
    .filter((pr) => BEHAVIOR_RE.test(textOf(pr)))
    .map((pr) =>
      prItem(
        pr,
        "Docs/release impact candidate",
        66,
        "The PR title or body suggests user-visible behavior, API, config, or CLI change.",
        ["Behavior/config/API language detected", `${pr.daysStale}d stale`, `${pr.comments + pr.reviewComments} comments`],
        "Check whether docs and release notes are part of the PR before merge review."
      )
    );

  const securityThreads = [
    ...securityIssues.map((issue) =>
      issueItem(issue, "Security-looking issue", 95, "Public issue includes security-sensitive language.", ["Security keyword detected"], "Route to a trusted maintainer for private review.")
    ),
    ...securityPrs.map((pr) =>
      prItem(pr, "Security-looking PR", 88, "PR includes security-sensitive language.", ["Security keyword detected"], "Review with extra care and verify tests/threat model.")
    ),
  ];

  const queueHealth: QueueHealth = {
    openIssues: issues.length,
    openPrs: prs.length,
    stalePrs: stalePrs.length,
    missingRepro: noReproIssues.length,
    likelyAiSlop: aiIssueItems.length + aiPrItems.length,
    securityLooking: securityIssues.length + securityPrs.length,
  };

  const topActions = [...securityThreads, ...riskyPrs, ...issueTriage, ...duplicateCandidates, ...docsReleaseImpact, ...aiIssueItems, ...aiPrItems]
    .sort((a, b) => b.score - a.score)
    .filter((entry, index, entries) => entries.findIndex((candidate) => candidate.id === entry.id) === index)
    .slice(0, 12);

  return {
    generatedAt: new Date().toISOString(),
    repo,
    queueHealth,
    summary: `${topActions.length} attention candidates from ${issues.length} issues and ${prs.length} PRs. ${queueHealth.likelyAiSlop} likely AI slop/disclosure items, ${queueHealth.securityLooking} security-looking threads.`,
    topActions,
    aiSlop: [...aiIssueItems, ...aiPrItems].sort((a, b) => b.score - a.score).slice(0, 12),
    riskyPrs: riskyPrs.sort((a, b) => b.score - a.score).slice(0, 12),
    issueTriage: issueTriage.sort((a, b) => b.score - a.score).slice(0, 12),
    duplicateCandidates: duplicateCandidates.sort((a, b) => b.score - a.score).slice(0, 8),
    docsReleaseImpact: docsReleaseImpact.sort((a, b) => b.score - a.score).slice(0, 8),
    securityThreads: securityThreads.sort((a, b) => b.score - a.score).slice(0, 8),
    deepNotes: [],
  };
}

